# Generated by Django 3.2.6 on 2021-08-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_auto_20210815_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_books', to='books_app.User'),
        ),
    ]
